### ISSUE TITLE
Clarify if CCF is balanced or not

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/cose-merkle-tree-proofs#1]
See https://www.rfc-editor.org/rfc/rfc6962#section-2.1

**Comment by achamayou** [comment]
@OR13 it's not. See https://microsoft.github.io/CCF/main/architecture/merkle_tree.html for details, the implementation lives under https://github.com/microsoft/merklecpp.

In general, at least the left half of the tree is balanced, and a variable portion on the right isn't. It sometimes becomes briefly balanced, before another subtree grows on right etc.

**Comment by OR13** [comment]
Let's close
