### ISSUE TITLE
re the todo keccak vs sha3

### ISSUE THREAD

**Issue by robinbryce** [ietf-scitt/cose-merkle-tree-proofs#17]
https://github.com/ietf-scitt/cose-merkle-tree-proofs/blob/28133f3d1c1041aabcb486400dac39887fd92679/python/merkle_proofs/tree_algorithms.py#L430

It's not. NIST tweaked keccak. The keccak team talk about it here: https://keccak.team/2013/yes_this_is_keccak.html

pycryptodome is my goto for keccak in python. pysha3 usualy gives me build woes.

**Comment by OR13** [comment]
i'm going to close this for now, we're migrating the spec to ietf cose wg repo, and we will probably drop the test code in that process.

**Comment by OR13** [comment]
See https://github.com/cose-wg/draft-ietf-cose-merkle-tree-proofs
