### ISSUE TITLE
Define the QLDB Tree algorithm

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/cose-merkle-tree-proofs#3]
https://docs.aws.amazon.com/qldb/latest/developerguide/verification.html

**Comment by letmaik** [comment]
https://docs.aws.amazon.com/qldb/latest/developerguide/verification.tutorial-block-hash.html#verification.tutorial.full

**Comment by letmaik** [comment]
Related to https://github.com/ietf-scitt/cose-merkle-tree-proofs/issues/7#issuecomment-1422905431, I'm wondering why hash pairs are sorted in QLDB. Isn't it important to know that one document revision happened before another revision?

**Comment by letmaik** [comment]
Looking at https://docs.aws.amazon.com/qldb/latest/developerguide/journal-contents.html they seem to resolve the issue at the payload layer, by referencing a previous transaction/block by hash and essentially creating a linked list. The Merkle tree then simply says whether a block is a member, and the linked list establishes ordering.

**Comment by letmaik** [comment]
From https://docs.aws.amazon.com/qldb/latest/developerguide/verification.results.html:

> First, pair your Revision hash with the first hash in the Proof hashes list. Then, do the following steps.
> 1. Sort the two hashes. Compare the hashes by their signed byte values in little-endian order.
> 2. Concatenate the two hashes in sorted order.
> 3. Hash the concatenated pair with an SHA-256 hash generator.
> 4. Pair your new hash with the next hash in the proof and repeat steps 1–3. After you process the last proof hash, your new hash is your recalculated digest.
