### ISSUE TITLE
Define the Trllion Tree algorithm

### ISSUE THREAD

**Issue by OR13** [ietf-scitt/cose-merkle-tree-proofs#4]
https://github.com/google/trillian/blob/6ff130e23e0c5e931b5cb78fef8a059ec32f7308/docs/VerifiableDataStructures-Latest.md

**Comment by letmaik** [comment]
Trillian's verifiable log data structure is the one used in the wild (as opposed to the others in the document) and is used by CT and Rekor/Sigstore. It is the one I named `RFC6962_SHA256` in the spec. We could rename it to TrillianLog_SHA256 but I think the RFC is a better reference.

**Comment by OR13** [comment]
The RFC is indeed the better source, I'm going to close this as completed.
